

name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 60aaf855ba2e15e20d0efbe440c8ff071b719580

    - name: Build C Code
      run: |
        autoreconf -h 
        autoreconf -fvi   
        ./configure 
        make 
